### ISSUE TITLE
Wrong Alignment of sub heading , separating about us and developer and making website logo used to navigate to top

### ISSUE THREAD

**Issue by jaydeep099** [mindspace-prototype/MindSpace#136]
In The website , I detect three bugs  that i can solve
1) Wrong alignment of sub heading like organisazions, books , talks and conference. 
2) Separating two section is very need in a website like about us and developer.
3) User always wants that when click he/she redirect to the top or home page.

I believe that i can solve as assign this task under gssoc 2024

**Comment by Agrima11** [comment]
hii...plss assign this issue to me
m proficient in html

**Comment by AaryaDandapur** [comment]
Hello!
Please assign this issue to me.
