### ISSUE TITLE
Contact Section

### ISSUE THREAD

**Issue by nisargaa20** [mindspace-prototype/MindSpace#139]
I will add contact section at the bottom of the webpage.  So that users can contact admin if they have any issues.

kindly assign me this issue #gssoc24

**Comment by hussain123sahil** [comment]
I can resolve this issue. Please assign me this issue.

**Comment by paridhi1509** [comment]
I would like to work on this issue by creating a contact us option where i plan on adding links to the social platforms.
Please assign me this issue.

**Comment by MrPC7** [comment]
I would like to resolve this issue by adding all the social media pages/links and also add an form where use can write his message and this will received to admins email.

Please assign it to me if you think my solution is beneficial to this problem.

Also you can suggest me what I can more add to this.

Thanks

**Comment by gargimukherjee25** [comment]
Hello I am Gargi from IIT Kharagpur! I work with html,css,js,react.js and so on and am eager to learn more. I'd appreciate being assigned this task for GSSoC 24.

**Comment by satyaveni299** [comment]
assign me this issue #gssoc24

**Comment by Sudiksha18** [comment]
please assign me under gssoc24
