### ISSUE TITLE
[Bug] Applications - anxio.us leads to Server Not Found error

### ISSUE THREAD

**Issue by ShreeluSantosh** [mindspace-prototype/MindSpace#142]
In dashboard.html page, one of the websites under Applications, anxio.us leads to a website named weareanxio.us which currently cannot be reached.

**Steps to reproduce the issue:**

1. In the index.html page, click on "Find Your Space" button. It will take you to the dashboard.html page
2. There, under Applications heading, you will find a bubble named Anxio.us.
3. Clicking this bubble redirects to weareanxio.us which returns the following error: Server Not Found

On researching more about anxio.us, I found that weareanxio.us had been purchased and deployed to Netlify. 

The correct link is: https://we-are-anxio.netlify.app/

I can fix this issue if it is assigned to me, under #gssoc24

**Comment by Sourav-Parida** [comment]
please assign this issue to me i want to work on this isuue
