### ISSUE TITLE
Footer section Unavailable!!!

### ISSUE THREAD

**Issue by Anjaliavv51** [mindspace-prototype/MindSpace#172]
Hello PA!

Assign this issue under GSSOC'24 
I would like add footer section , which contains contacts details.
![image](https://github.com/The-MindSpace/MindSpace-Web/assets/154777864/785cc122-6f9f-4bbe-aef8-6bcbfbc0d5a0)

Could you assign this issue to me? I’d love to dive in and fix it! 🛠️

**Comment by reshamsai150** [comment]
footer plays a vital role in maximizing user experience, A footer makes your site look professional and complete. Websites without footers may appear incomplete assign this  issue to me , I am interested in working on this issue

**Comment by safael-alami** [comment]
The footer, with navigation, contact details, legal info, and social links, improves UX and ensures compliance. I'd be eager to handle this; could you assign it to me?

**Comment by ghost** [comment]
please assign me this issue
