### ISSUE TITLE
The website lacks responsiveness!

### ISSUE THREAD

**Issue by Anjaliavv51** [mindspace-prototype/MindSpace#173]
Please assign this issue under GSSOC'24 
I intend to enhance the website’s responsiveness and address the issue related to the improper wrapping of circles. I would like to work on resolving these issues.🌐🛠️
![image](https://github.com/The-MindSpace/MindSpace-Web/assets/154777864/854bac27-8ecd-4b81-aa6b-36eb861c070b)

Once it is opened in mobile nav bar is also unavailable
![image](https://github.com/The-MindSpace/MindSpace-Web/assets/154777864/49ad141b-58e8-444e-9561-23312aca049d)
![image](https://github.com/The-MindSpace/MindSpace-Web/assets/154777864/6154ebb8-0ae0-4d8b-b713-bbd710f2de6e)

Could you assign this issue to me? I’d love to dive in and fix it! 🛠️🚀
Thank You!!!

**Comment by YB11102004** [comment]
I would love to work on this issue please assign it to me under GSSOC'24.
